// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://hxftiocfihhdutciaisl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imh4ZnRpb2NmaWhoZHV0Y2lhaXNsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjcwMDM5MDIsImV4cCI6MjA4MjU3OTkwMn0.2DxedsU5prsd9GhFH4dJA2I1HbYhiGLhHBcNOVjjEjk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);